import { StyleSheet } from 'react-native';
import colors from 'src/styles/texts/colors';
import fonts from 'src/styles/texts/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  titleAndBudgetContainer: {
    flexDirection: 'row',
    paddingTop: 20,
    justifyContent: 'space-between',
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  titleText: {
    flex: 0.9,
    color: colors.skyBlue,
    fontSize: 18,
    textAlign: "left",
    fontFamily: fonts.primarySB,
  },
  budgetText: {
    color: colors.appViolet,
    fontSize: 16,
    textAlign: "left",
    fontFamily: fonts.secondarySB,
  },
  experienceAndTimeContainer: {
    flexDirection: 'row',
    paddingBottom: 20,
    justifyContent: 'space-between',
  },
  experienceText: {
    color: colors.appGray,
    fontSize: 14,
    textAlign: "left",
    fontFamily: fonts.secondary,
  },
  timeText: {
    color: colors.appGray,
    fontSize: 12,
    textAlign: "left",
    fontFamily: fonts.primary,
  },
  postedBy: {
    fontFamily: fonts.primarySB,
    color: colors.appBlack,
    fontSize: 16,
    textAlign: "left",
    paddingBottom: 5,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  locationText: {
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appBlack,
  },
  description: {
    paddingVertical: 10,
    borderBottomColor: colors.appGray,
    borderBottomWidth: 0.5,
    fontSize: 14,
    textAlign: "left",
    color: colors.appBlack,
  },
  timelineText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appGray,
  },
  timelineInfo: {
    fontFamily: fonts.secondarySB,
    fontSize: 18,
    textAlign: "left",
    color: colors.appBlack,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  milestoneText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appGray,
  },
  freelancerText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 14,
    textAlign: "left",
    color: colors.appGray,
  },
  milestoneInfo: {
    fontFamily: fonts.secondarySB,
    fontSize: 16,
    textAlign: "left",
    color: colors.appBlack,
    paddingVertical: 5,
  },
  milestonePrice: {
    fontFamily: fonts.secondarySB,
    fontSize: 16,
    textAlign: "left",
    color: colors.appViolet,
    // paddingBottom: 10,
    textAlignVertical: 'center',

    // borderBottomColor: colors.appGray,
  },
  milestoneItem: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
    alignItems: 'center',
    textAlignVertical: 'center',
  },
  skillsText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appGray,
  },
  skillsInfo: {
    fontFamily: fonts.primarySB,
    fontSize: 18,
    textAlign: "left",
    color: colors.appBlack,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  projectIdText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appGray,
  },
  projectIdInfo: {
    fontFamily: fonts.primarySB,
    fontSize: 18,
    textAlign: "left",
    color: colors.appBlack,
    paddingBottom: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  attachmentText: {
    paddingTop: 10,
    paddingBottom: 5,
    fontFamily: fonts.primary,
    fontSize: 12,
    textAlign: "left",
    color: colors.appGray,
  },
  attachmentContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 5,
    // justifyContent: 'space-between',
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  attachmentImage: {
    width: 60,
    height: 60,
  },
  attachmentOuterContainer: {
    paddingBottom: 10,
  },
  attachmentName: {
    marginStart: 20,
    textAlign: 'left',
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    padding: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: colors.appGray,
  },
  headerLeft: {
    marginEnd: 10,
    alignSelf: 'auto',
  },
  image: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignSelf: 'center',
  },
  headerRight: {
    flex: 1,
  },
  headerRightTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: 10,
    textAlignVertical: 'center',
  },
  freelancerName: {
    fontSize: 18,
    textAlign: "left",
    fontFamily: fonts.primarySB,
    color: colors.skyBlue,
  },
  freelancerRate: {
    fontSize: 18,
    textAlign: "left",
    fontFamily: fonts.primarySB,
    color: colors.appViolet,
    textAlign: 'left',
  },
  headerRightCenter: {
    fontSize: 14,
    textAlign: "left",
    fontFamily: fonts.secondary,
    color: colors.appViolet,
    textAlign: 'left',
  },
  headerRightBottom: {
    flexDirection: 'row',

    justifyContent: 'space-between',
  },
  headerRightBottomLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationName: {
    fontSize: 12,
    textAlign: "left",
    fontFamily: fonts.primary,
    color: colors.appGray,
    textAlign: 'left',
  },
  successRate: {
    fontSize: 12,
    textAlign: "left",
    fontFamily: fonts.primary,
    color: colors.appGray,
    textAlign: 'left',
  },
});

export default styles;
