require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Qaff_Freelancer' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

#  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
pod 'GoogleSignIn', '~> 5.0.2'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  target 'Qaff_FreelancerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Qaff_Freelancer-tvOS' do
  # Pods for Qaff_Freelancer-tvOS

  target 'Qaff_Freelancer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
